from __future__ import annotations

import io
from xhtml2pdf import pisa


def generate_paper_pdf(paper_data: dict) -> bytes:
    """
    Generates a PDF byte stream from paper data.
    """
    subject = paper_data.get("subject", "Examination")
    total_marks = paper_data.get("total_marks", 0)
    questions = paper_data.get("questions", [])

    html_content = f"""
    <html>
    <head>
        <style>
            @page {{
                size: a4;
                margin: 2cm;
            }}
            body {{
                font-family: 'Helvetica', 'Arial', sans-serif;
                color: #333;
                line-height: 1.6;
            }}
            .header {{
                text-align: center;
                border-bottom: 2px solid #333;
                margin-bottom: 20px;
                padding-bottom: 10px;
            }}
            .header h1 {{ margin: 0; font-size: 24px; }}
            .header p {{ margin: 5px 0; font-size: 14px; text-transform: uppercase; }}
            .metadata {{
                display: flex;
                justify-content: space-between;
                margin-bottom: 30px;
                font-weight: bold;
            }}
            .question-container {{
                margin-bottom: 20px;
            }}
            .question-header {{
                font-weight: bold;
                margin-bottom: 5px;
            }}
            .marks {{
                float: right;
            }}
            .footer {{
                position: fixed;
                bottom: 0;
                width: 100%;
                text-align: center;
                font-size: 10px;
                color: #777;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>STARK INDUSTRIES INSTITUTE</h1>
            <p>Department of {subject}</p>
            <p>Annual Examination Question Paper</p>
        </div>

        <table style="width: 100%; margin-bottom: 20px;">
            <tr>
                <td style="text-align: left;"><strong>Subject:</strong> {subject}</td>
                <td style="text-align: right;"><strong>Total Marks:</strong> {total_marks}</td>
            </tr>
            <tr>
                <td style="text-align: left;"><strong>Time:</strong> 3 Hours</td>
                <td style="text-align: right;"><strong>Set:</strong> AI-Generated (Smart)</td>
            </tr>
        </table>

        <div class="instructions">
            <strong>Instructions:</strong>
            <ul>
                <li>All questions are compulsory.</li>
                <li>Draw neat diagrams where necessary.</li>
                <li>Figures to the right indicate full marks.</li>
            </ul>
        </div>

        <hr/>

        <div class="questions">
    """

    for q in questions:
        html_content += f"""
            <div class="question-container">
                <div class="question-header">
                    Q{q['question_no']}. [{q['topic']}]
                    <span class="marks">({q['marks']} Marks)</span>
                </div>
                <div class="question-text">
                    {q['question_text']}
                </div>
            </div>
        """

    html_content += """
        </div>
        <div class="footer">
            Generated by AI-Based Question Paper Intelligence System © 2026
        </div>
    </body>
    </html>
    """

    pdf_output = io.BytesIO()
    pisa_status = pisa.CreatePDF(io.StringIO(html_content), dest=pdf_output)

    if pisa_status.err:
        raise Exception("Error generating PDF")

    return pdf_output.getvalue()
